### ISSUE TITLE
fatal error: runtime: out of memory

### ISSUE THREAD

**Issue by Hanker-13** [xujiajun/nutsdb#105]
**Describe the bug**
Hello, I want to do a simple function of network disconnection and continuous transmission of timing data. I rpush the time sequence data after disconnection into a list. After the network connection replies, the data is lpop from the list and sent through mqtt. However, memory overflow often occurs when fetching data. What should I do?

`fatal error: runtime: out of memory`

OS: `Linux am335x 3.2.0 #595 Wed Jan 31 00:13:29 PST 2018 armv7l GNU/Linux`

**Comment by Hanker-13** [comment]
Yes, there is not enough memory for allocation. My arm board has about 250MB of memory.
The data file is about 80mb in total, and there is only one list. I periodically send pop data from this list.

**Comment by xujiajun** [comment]
@Hanker-13 What version of NutsDB are you using, can you show me the code you wrote?

**Comment by xujiajun** [comment]
I'll close it first. If there is a problem, you can raise the issue again.
