### ISSUE TITLE
It is possible to run "in memory"?

### ISSUE THREAD

**Issue by ecerichter** [xujiajun/nutsdb#108]
Hi!
I've found nutsdb nearly perfect for my project.
Nevertheless, I would like to know if it is possible to use it exclusively as in-memory database (without persistence)?

Thanks in advance,

ER.

**Comment by xujiajun** [comment]
@ecerichter 
Hi, Thank you for your attention. When NutsDB is designed, it will be persistent. You want it to be non-persistent. Currently, there is no such feature. I am curious. What scene do you use? Is it cached locally?

**Comment by ecerichter** [comment]
I've few dozens of microserviços running heavy calculations, and I would like to avoid going to database to collect data that can be cached. 
For example, one search of zip code takes near 3ms to happen in traditional SQL database. Few days ago, I've converted to a range search (using standard B-tree algorithm), and time decreased from 3ms to 250ns. It's a huge gain for a service that needs to finish it's complete calculations in 20ms.
My servers are plenty of memory, so I'm considering to use all auxiliary tables in memory - some have only 300 records (too expensive for a database round trip), others have million of records (too big to wait for database build a cache).
We don't need to store anything in this microservice since all data is loaded from SQL database during startup sequence.
I've considered other KV "in-memory" databases, but they lack some features, like range searches, which are vital for my work.
Nutsdb have them all.
Finally, we work with the concept of "data versioning" - so, when user updates data, microservices detected that change, it starts loading a new version of all data and then comute to use them (so, the system never stops); after comute, old version of data is removed from memory.

**Comment by xujiajun** [comment]
@ecerichter "For a service that needs to complete a complete calculation within 20 milliseconds, this is a huge gain." This sentence impressed me deeply. This is a meaningful feature. Okay, I understand. You need the index function of nutsdb, but don't use the function of persistence. You don't need to consider the problem of data loss due to memory mode and restart in your scenario. I can support you because I have to work during the day and spend time at night to help you develop this feature. It can be completed as soon as this week. Thank you for your attention.

**Comment by xujiajun** [comment]
@ecerichter Sorry, I thought this feature was developed very quickly, but it actually took a lot of time, mainly because I didn't have much time. I have established a branch, you can take a look at https://github.com/xujiajun/nutsdb/tree/feature/in_memory for details.

**Comment by ecerichter** [comment]
Don't worry. After talking with you, ocurred to me that I can reach a similar achievement using maps to build a balanced finite tree (map of keys of maps), and then use hash algoritm for searching data. It's not perfect, and would not be sustainable for larger projects - but for this one now, I can handle this complexity.
I do really appreciate your effort in developing this, and I'll keep an eye when ready to test. Unfortunately, I'm overwhelmed of tasks here, otherwise I would help you in this development.

**Comment by xujiajun** [comment]
Hi，NutsDB v0.7.1 already supports memory mode, you can try it when you have time :)
