### ISSUE TITLE
README 中文错字

### ISSUE THREAD

**Issue by zgat** [xujiajun/nutsdb#14]
天下没有银弹，NutsDB也有**他**的局限，比如随着数据量的增大，索引变大，启动会慢, 还有为了保持**保**->**高** 性能的写**如**->**入**，目前版本没有做实时的flush/sync操作，依赖内核的回写操作。只想说NutsDB还有很多优化和提高的空间，由于本人精力以及能力有限。所以把这个项目开源出来。更重要的是我认为一个项目需要有人去使用，有人提意见才会成长。

**Comment by xujiajun** [comment]
@zgat 感谢指出 已经fix，还有错误可以直接发我PR ；）
