### ISSUE TITLE
does golevel support transaction ?

### ISSUE THREAD

**Issue by ping40** [xujiajun/nutsdb#17]
https://godoc.org/github.com/syndtr/goleveldb/leveldb#DB.OpenTransaction 
as the doc says that golevel  does support transaction.

`
> GoLevelDB GoLevelDB 是 google 开源的 leveldb 的 go 语言版本的实现。他的性能很高，特别是写性能，据官方 c++版本说可以到 40w+次写 /秒，他基于 LSM tree 实现。他不支持事务。

`
为什么说 不支持呢 ？

**Comment by xujiajun** [comment]
@ping40  支持的 从doc api 上来看，应该是有的。我还没尝试。你截的描述，现在应该找不到了，应该之前的README。请以最新的master的readme为准。如果发现有问题，请及时指正，或者给我PR，谢谢关注。
