### ISSUE TITLE
这个支持跨语言调用吗？

### ISSUE THREAD

**Issue by pilgrimzh** [xujiajun/nutsdb#25]

**Comment by pilgrimzh** [comment]
比如我用java/C#，想使用nutsdb数据库,怎么调用。有没有统一的调用接口说明文档？

**Comment by xujiajun** [comment]
@pilgrimzh 当前版本的nutsDB定位是内嵌型的，如果你要想跨语言调用，需要自己封装下即可。比如你要用rpc，你可以用grpc（支持多语言的rpc就行）的go版本，加上nutsDB进行封装成server端，供多语言的客户端调用。比如你要用http的调用， example 里面有个封装http server的例子你可以参考下：https://github.com/xujiajun/nutsdb/blob/master/examples/http/main.go

接口文档：https://godoc.org/github.com/xujiajun/nutsdb
还有README也有使用说明。

**Comment by pilgrimzh** [comment]
好的，感谢~
