### ISSUE TITLE
Timeline for productionizing this DB

### ISSUE THREAD

**Issue by ishail** [xujiajun/nutsdb#28]
Hi @xujiajun,

Do we have a checklist, which is being tracked to make this production-ready? What are the major issues we are facing to have it production-ready?

**Comment by xujiajun** [comment]
@ishail ,  yes we have checklist, but not public to visit,  and i has completed all short-term issues, the next arrangement is mainly maintenance and repair bugs, etc., as well as planning distributed solutions.
Actually the version 0.4.0 is production ready. Someone has used it in the production environment.

**Comment by ishail** [comment]
Cool, Thanks for quick update! 👍
