### ISSUE TITLE
db.buildIndexes error: err EntryIdxMode option set

### ISSUE THREAD

**Issue by googolgl** [xujiajun/nutsdb#30]
```
opt := nutsdb.DefaultOptions
	opt.Dir = "./nutsdb"
	opt.SegmentSize = 8388608
	opt.EntryIdxMode = nutsdb.HintKeyAndRAMIdxMode
	opt.SyncEnable = true
	opt.RWMode = nutsdb.FileIO
	opt.NodeNum = 1
```

Can`t start connect to db if set **HintKeyAndRAMIdxMode**.
First start is normal , but second start showing error.

**Comment by xujiajun** [comment]
@googolgl hi, Please provide more information.
0、nutsDB version ?
1、which Platform？  e.g. OS X 10.13.6, Ubuntu 16.04
2、the code you execute ?

Then I will check this question. thanks.

**Comment by googolgl** [comment]
1. github.com/xujiajun/nutsdb v0.4.1-0.20190405142137-dad030248b51
2. Ubuntu 18.04.2 LTS; Linux Comp 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux; Intel(R) Pentium(R) CPU G2120 @ 3.10GHz; Mem 8096328
3. 
```golang
import "github.com/xujiajun/nutsdb"

type ndb struct {
	db *nutsdb.DB
}

func initNutsdb() *nutsdb.DB {
opt := nutsdb.DefaultOptions
opt.Dir = "./nutsdb"
opt.SegmentSize = 8388608
opt.EntryIdxMode = nutsdb.HintKeyAndRAMIdxMode
opt.SyncEnable = false
opt.RWMode = nutsdb.FileIO
opt.NodeNum = 1
db, err := nutsdb.Open(opt)
if err != nil {
	log.Fatal(err)
}
return db
}

in main function
n = ndb{
      db: initNutsdb(),
}
```

**Comment by xujiajun** [comment]
@googolgl ,hi ,  
I used your code (fixed some syntax mistake) to run on ubuntu 18.04.2 LTS multiple times, but no errors occurred.

The code that runs is as follows：

```
package main

import "github.com/xujiajun/nutsdb"


func initNutsdb() *nutsdb.DB {
	opt := nutsdb.DefaultOptions
	opt.Dir = "./nutsdb_data"
	opt.SegmentSize = 8388608
	opt.EntryIdxMode = nutsdb.HintKeyAndRAMIdxMode
	opt.SyncEnable = false
	opt.RWMode = nutsdb.FileIO
	opt.NodeNum = 1
	db, err := nutsdb.Open(opt)
	if err != nil {
		panic(err)
	}
	return db
}

func main() {
	initNutsdb()
}

```

BTW the latest version of nutsDB is 0.4.0 ，why `github.com/xujiajun/nutsdb v0.4.1-xxx` ?

**Comment by googolgl** [comment]
It's my mistake.
Before saving data i needed serialize them.
Now all is fine.

**Comment by googolgl** [comment]
how can i get all keys from bucket if i know only  bucket name?
in analogi ForEach() function on boltdb.
Thanks

**Comment by googolgl** [comment]
it's my mistake
thanks
