### ISSUE TITLE
ForEach() function like in boltdb

### ISSUE THREAD

**Issue by googolgl** [xujiajun/nutsdb#32]
Can you add a similar ForEach() function like in boltdb?
if i known only bucket name and want get all keys, values.
Thanks

**Comment by xujiajun** [comment]
@googolgl hi, 
I don't recommend using foreach for unlimited output of all keys and values, especially in the case of a lot of data, I suggest creating a bucket based on the business, you can do a range scan operation based on the start and end of the key , like this:

```
if err := db.View(
	func(tx *nutsdb.Tx) error {
		start := []byte("user_0000001") // start key
		end := []byte("user_0000010") // end key
		bucket：= []byte("user_list") // bucket 
		if entries, err := tx.RangeScan(bucket, start, end); err != nil {
			return err
		} else {
			keys, es := nutsdb.SortedEntryKeys(entries)
			for _, key := range keys {
				fmt.Println(key, string(es[key].Value))
			}
		}
		return nil
	}); err != nil {
	log.Fatal(err)
}
```



If you really need this feature, I can also consider adding it to the later version :)

**Comment by googolgl** [comment]
It's really needed feature.
Now i use that's variant:
tx.Prefix Scan(bucket, []byte(""), 100000)
but think it`is not correct idea

**Comment by xujiajun** [comment]
@googolgl  ok, it will be supported in the next version ：）

**Comment by xujiajun** [comment]
hi, v0.5.0 has released, you can try it :) ,changelog here :https://github.com/xujiajun/nutsdb/issues/50
