### ISSUE TITLE
list set等类型的数据在内存和磁盘都存储了一次

### ISSUE THREAD

**Issue by xww** [xujiajun/nutsdb#35]
从代码上看，无论是HintKeyAndRAMIdxMode还是HintKeyValAndRAMIdxMode， list等类型的数据都会在磁盘写一份，func (tx *Tx) Commit() error {}逻辑里面并不区分具体的数据结构，都一股脑往磁盘里面写进去，同时tx.buildIdxes(writesLen)又会把数据全部写在内存的list链表里面一次，是这样的吗？如果我理解的没错，觉得这是个大问题

**Comment by xujiajun** [comment]
@xww ，谢谢关注。你好，
1 关于你说的 `func (tx *Tx) Commit() error {}` 这边的数据在持久化到磁盘前，肯定是做了数据结构区分的，不然怎么做索引。
2 关于你说的 `同时tx.buildIdxes(writesLen)又会把数据全部写在内存的list链表里面一次` 这个是根据不同的数据结构建立对应的索引，不你说的`会把数据全部写在内存的list链表里面一次`。

另外 nutsdb 的确还存在很多不足 ，欢迎指出，一起讨论，改善。

**Comment by xww** [comment]
但是你看下面的代码，你为list类型的数据创建索引，确实是吧key和value都在内存中保存了一份啊？这个我没有理解错吧？也就是说磁盘有一份，内存的索引其实还有一份，这个索引并不是key+value的地址，而是直接就是key+value，对吧？
func (tx *Tx) buildListIdx(bucket string, entry *Entry) {
	if _, ok := tx.db.ListIdx[bucket]; !ok {
		tx.db.ListIdx[bucket] = list.New()
	}

	key, value := entry.Key, entry.Value

	switch entry.Meta.Flag {
	case DataLPushFlag:
		_, _ = tx.db.ListIdx[bucket].LPush(string(key), value)

**Comment by xujiajun** [comment]
是的。对于list类型的确是内存和磁盘都存了一份。
