### ISSUE TITLE
Getting `err bucket` in LSet

### ISSUE THREAD

**Issue by ishail** [xujiajun/nutsdb#36]
### Issue
I'm not able to execute `tx.LSet` over db object. It throws the error `err bucket`. Although it is working fine for `tx.Get` as well as `tx.Set`.

### Version
`v0.4.0`

### Sample code
```
if err := db.Update(
	func(tx *nutsdb.Tx) error {
		if err := tx.LSet(bucket, key, 0, values[0]); err != nil {
			return err
		}

		return nil
	}); err != nil {
        fmt.Println(err.Error())
}
```

**Comment by xujiajun** [comment]
@ishail , hi , you should execute  `LPush` or `RPush` function before execute `LSet` function, like this:

```go
        if err := db.Update(
		func(tx *nutsdb.Tx) error {
			key := []byte("myList")
			val := []byte("val1")
			return tx.LPush(bucket, key, val)
		}); err != nil {
		log.Fatal(err)
	}

	if err := db.Update(
		func(tx *nutsdb.Tx) error {
			key := []byte("myList")
			updateVal := []byte("val11")
			err := tx.LSet(bucket, key, 0, updateVal)
			if err != nil {
				return err
			}
			fmt.Println("LSet ok, index 0 item value => val11")
			return nil
		}); err != nil {
		log.Fatal(err)
	}
```

**Comment by ishail** [comment]
Thanks @xujiajun, it works :-)

**Comment by ishail** [comment]
What would be the intuitive to replace a list in NutsDB with new set of values?
Example: I want to put a list of values(`["1", "2", "3"]`) in the db, but later replace the list will new list(`["4", "5", "6", "7"]`).

Right now, I'm trying to use `LSize` or `LRange` to check whether key is present in the list or not, and then use `LPush` or `LSet` accordingly. But `LSize` and `LRange` doesn't respond anything if key is not present.

@xujiajun, I appreciate the help! :-)
