### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by ayaya118** [xujiajun/nutsdb#39]
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/xujiajun/nutsdb.(*DB).getMaxFileIDAndFileIDs(0xc000044aa0, 0x0, 0xc000069d28, 0x81f8ec, 0x91d5bc)
	D:/gopath/src/github.com/xujiajun/nutsdb/db.go:347 +0x33d
github.com/xujiajun/nutsdb.(*DB).buildIndexes(0xc000044aa0, 0x3, 0x30000076f25401)
	D:/gopath/src/github.com/xujiajun/nutsdb/db.go:616 +0x36
github.com/xujiajun/nutsdb.Open(0x91d5bc, 0x3, 0x0, 0x0, 0x800000, 0x1, 0x1, 0x1, 0xa509ff, 0xc000069eb8, ...)
	D:/gopath/src/github.com/xujiajun/nutsdb/db.go:174 +0x164
leibe.cn/roomMessageOutput/db/ndb.GetNDB(0xd79500)
	D:/gopath/src/leibe.cn/roomMessageOutput/db/ndb/ndb.go:12 +0xc5
main.main()
	D:/gopath/src/leibe.cn/roomMessageOutput/easy.go:16 +0x3b

代码：
package ndb

import (
	"github.com/xujiajun/nutsdb"
	"log"
)
var NDB *nutsdb.DB

func GetNDB() *nutsdb.DB {
	opt := nutsdb.DefaultOptions
	opt.Dir = `./`
	NDB, err := nutsdb.Open(opt)
	if err != nil {
		log.Fatal(err,NDB)
	}
	return NDB
}

**Comment by xujiajun** [comment]
@ayaya118 你好，你的`opt.Dir ` 设置有问题，你改成全路径，或者你一定要相对路径 ， 改成 `opt.Dir =“./xxx” `试试 (xxx是你需要存的目录)。

**Comment by ayaya118** [comment]
试了下，好像只能存放到 临时目录 ，其他目录都不行，Linux也这样。能拉我进微信群吗？我微信：wucheng1985

**Comment by ayaya118** [comment]
![图片](https://user-images.githubusercontent.com/4150721/59730157-dc835680-9273-11e9-883c-d03406019877.png)

**Comment by xujiajun** [comment]
@ayaya118 好的。已经加了哦
