### ISSUE TITLE
constant 2147483648 overflows int

### ISSUE THREAD

**Issue by dragonvc** [xujiajun/nutsdb#40]
GOARCH=386
GOOS=windows
github.com\xujiajun\nutsdb\ds\zset\sortedset.go:291:13: constant 2147483648 overflows int
查看代码发现有一个初始值：
limit := 1 << 31

limit值int型

**Comment by xujiajun** [comment]
@dragonvc  最新master 已经修复。https://github.com/xujiajun/nutsdb/commit/c70feeae6f1a8b483ae536d35b04717613ab1091
