### ISSUE TITLE
ErrKeyNotFound and ErrNotFoundKey

### ISSUE THREAD

**Issue by dragonvc** [xujiajun/nutsdb#42]
如果我没有保存过一个key，我尝试去get它，返回错误 ErrKeyNotFound
if i never put a key, i  get it , it will return ErrKeyNotFound.

如果我曾经保存过一个key，然后删除了，接着又尝试去get它。返回错误ErrNotFoundKey。
if i had put a key, then delet it , now i get it , it will return ErrNotFoundKey.

请教一下，这两个错误的意思的区别是什么呢？难道我使用过程中还得区分它们吗？
could your tell me different between ErrKeyNotFound and ErrNotFoundKey?

thanks  ..

**Comment by xujiajun** [comment]
hi, @dragonvc 
ErrKeyNotFound is returned when the key is not in the index.
ErrNotFoundKey is returned when the key is not found int the bucket on a view function.
Whether to distinguish this error depends on you, generally does not need to distinguish.
