### ISSUE TITLE
GetAll() function does not work with HintBPTSparseIdxMode 

### ISSUE THREAD

**Issue by Ice3man543** [xujiajun/nutsdb#43]
**Describe the bug**
Iterating the key-value store doesn't work with HintBPTSparseIdxMode indexing option.

**To Reproduce**
Steps to reproduce the behavior(Be specific!): Run this

```go
err := c.db.View(
		func(tx *nutsdb.Tx) error {
			entries, err := tx.GetAll(bucketName)
			if err != nil {
				return err
			}

			for _, entry := range entries {
				callback(entry.Key, entry.Value)
			}
			return nil
		},
	)
```

**Expected behavior**
Keys and values should be iterated.

**What actually happens**
It says bucket not found, while debugging, i see that the routine doesn't has a separate function for ActiveBPTTree, and instead it works with normal indexing.

**Screenshots**

This seems like the issue  - 
```go
if index, ok := tx.db.BPTreeIdx[bucket]; ok {
		records, err := index.All()
		if err != nil {
			return nil, ErrBucketEmpty
		}

		entries, err = tx.getHintIdxDataItemsWrapper(records, ScanNoLimit, entries, RangeScan)
		if err != nil {
			return nil, ErrBucketEmpty
		}
	}
```
**please complete the following information :**
 - OS: Ubuntu 16.04
 - NutsDB Version Latest

**Comment by Ice3man543** [comment]
I'd like to help you with this and another issue i've opened if you can guide me a bit on the issues here and what it would require to make it compatible.

**Comment by xujiajun** [comment]
hi @Ice3man543 , 

This is a bug that is not compatible with the latest mode: HintBPTSparseIdxMode.
if you want to help me to fix it, please give me your pull request. thanks:)

**Comment by Ice3man543** [comment]
Hey, I'd love some pointers on how to fix the issue

**Comment by xujiajun** [comment]
Hi, you can refer to the implementation of these methods: `func (t *BPTree) getAll()` and `func (tx *Tx) Get(bucket string, key []byte)` .

**Comment by xujiajun** [comment]
@Ice3man543 , v0.5.0 has released, this issue has fixed. you can try it.
