### ISSUE TITLE
I am confused

### ISSUE THREAD

**Issue by nonpcnpc** [xujiajun/nutsdb#47]
I wanted to try this db. I wanted to set 10M keys, read them sequentially, then write 10k random values and read 10k random values. I did that with other databases(bolt, badger, bitcask..) so I wanted to compare nuts as well. The thing is that no matter what, the transaction just keeps on going. It creates these 8MB files and writes at under 3MB/s speed but no matter how long I wait, it just keeps on going without finishing.

I tried a single transaction and I tried multiple transactions and setting 100 values at a time, but the same result.

So I am quite baffled as to why this is happening?

**Comment by xujiajun** [comment]
@nonpcnpc hi ，
Cloud you provide your test code and tell me which branch or version of nutsdb you are using?

**Comment by nonpcnpc** [comment]
sorry, i dont have the code anymore. but it was smiple for loop with key and value being the integer set via binary.BigEndian.PutUint64. as for version - whatever go get downloaded :)

**Comment by nonpcnpc** [comment]
just fyi - this might be the same issue as https://github.com/akrylysov/pogreb/issues/25
