### ISSUE TITLE
example with GetAll doe not work

### ISSUE THREAD

**Issue by marcelloh** [xujiajun/nutsdb#48]
**Describe the bug**
tx.GetAll undefined (type *nutsdb.Tx has no field or method GetAll)

**To Reproduce**
```
	err := NDB.View(
		func(tx *nutsdb.Tx) error {
			entries, err := tx.GetAll(bucket)
			if err != nil {
				return err
			}

			for _, entry := range entries {
				fmt.Println(string(entry.Key), string(entry.Value))
			}

			return nil
		})
```

**Expected behavior**
tx.GetAll should be available, accoring to:
https://xujiajun.cn/nutsdb/#get-all

**What actually happens**
An error :-(

**please complete the following information :**
 - OS: Mac OS 10.14.6
 - NutsDB Version : 0.4.0

**Comment by xujiajun** [comment]
@marcelloh hi，
What error is reported？ could you provide your test code  ？

**Comment by marcelloh** [comment]
the error  is (during compile time):
tx.GetAll undefined (type *nutsdb.Tx has no field or method GetAll)
(which I mentioned at: Describe the bug

and I did give you example code too (see the above : to reproduce)

**Comment by marcelloh** [comment]
But here's my complete function:
```
/*
GetAll gets all entries in a bucket from the database.
*/
func GetAll(bucket string) (*nutsdb.Entries, error) {
	var (
		err     error
		records nutsdb.Entries
	)

	err = NDB.View(
		func(tx *nutsdb.Tx) error {
			records, err = tx.GetAll(bucket) // This line is not recognized
			if err != nil {
				if err.Error() == "range scans not found" {
					return nil
				}

				return err
			}

			return nil
		})

	return &records, err
}

```

**Comment by xujiajun** [comment]
@marcelloh  

I looked at the [0.4.0 version of the README](https://github.com/xujiajun/nutsdb/tree/v0.4.0). It is true that the 0.4.0 version does not support this feature(GetAll). What you see is the README of the master branch. If you want to try this feature，you can use the master branch.

**Comment by marcelloh** [comment]
ok. Clear. Does it mean dat a newer master will have no GetAll, or is branch 0.40 just "behind"?

**Comment by xujiajun** [comment]
Hi, [v0.5.0](https://github.com/xujiajun/nutsdb/releases/tag/v0.5.0) has release ，you can try this version :)

**Comment by marcelloh** [comment]
works :-) Thanks for the quick fixing !
