### ISSUE TITLE
Callback on evict by TTL

### ISSUE THREAD

**Issue by asyslinux** [xujiajun/nutsdb#52]
**Describe the solution you'd like**

Hello, NutsDB is great KV store. I want to use NutsDB in my big project and I look for callback function feature on key eviction by TTL. For example, "bigcache" project have a custom callback function (OnRemove). It is a be great if callback function will be in NutsDB.

In my case, I have a real files on the file system and TTL in memory KV store for these files. When TTL time for key is gone, then with callback I could do remove file from file system.

I think this is useful feature and may be easy to implement in NutsDB.

Thank You.

**Comment by asyslinux** [comment]
I sorry, i look in source code, NutsDB no have internal scheduler for checking TTL in all keys, if i all right understand code. I think I can write my own outside checker, and if have a nil response, then key is deleted or deleted by TTL when I make Get() request.

**Comment by xujiajun** [comment]
@asyslinux  your understanding is right:)
