### ISSUE TITLE
队列读取执行LPop，最终这个值还在？

### ISSUE THREAD

**Issue by rickyHuang1986** [xujiajun/nutsdb#56]
package main

import (
	"fmt"
	"github.com/xujiajun/nutsdb"
	"log"
	"os"
	"time"
)

var (
	DBBucket = "test"
	DBDir    = "/tmp/nutsdb"
)

func main() {
	_ = os.RemoveAll(DBDir)
	opt := nutsdb.DefaultOptions
	opt.Dir = DBDir
	db, err := nutsdb.Open(opt)
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()
	_ = db.Update(func(tx *nutsdb.Tx) error {
		key := []byte("testKey")
		tx.RPush(DBBucket, key, []byte(time.Now().String()))
		time.Sleep(time.Second)
		tx.RPush(DBBucket, key, []byte(time.Now().String()))
		time.Sleep(time.Second)
		tx.RPush(DBBucket, key, []byte(time.Now().String()))
		time.Sleep(time.Second)
		tx.RPush(DBBucket, key, []byte(time.Now().String()))
		time.Sleep(time.Second)

		return nil
	})

	_ = db.View(func(tx *nutsdb.Tx) error {
		key := []byte("testKey")

		b, _ := tx.LPop(DBBucket, key)
		fmt.Println(string(b))
		return nil
	})

	_ = db.View(func(tx *nutsdb.Tx) error {
		key := []byte("testKey")

		b, _ := tx.LPop(DBBucket, key)
		fmt.Println(string(b))
		return nil
	})

	_ = db.View(func(tx *nutsdb.Tx) error {
		key := []byte("testKey")

		b, _ := tx.LRange(DBBucket, key, 0, -1)
		for _, b1 := range b {
			fmt.Println(string(b1))
		}
		return nil
	})
}

**Comment by xujiajun** [comment]
@rickyHuang1986 ,你好，执行`tx.LPop`，应该是`db.Update`
