### ISSUE TITLE
是否支持获取所有的bucket信息，谢谢！

### ISSUE THREAD

**Issue by kafpost** [xujiajun/nutsdb#57]
在忘记某个bucket名字时，知道所有的bucket信息可能有帮助，谢谢！

**Comment by xujiajun** [comment]
@kafpost 可以支持，不过我最近很忙，等空点会增加这个feature。

**Comment by xujiajun** [comment]
v0.7.1 版本 已经实现迭代bucket。你可以尝试下。

中文文档：https://github.com/xujiajun/nutsdb/blob/master/README-CN.md#%E8%BF%AD%E4%BB%A3buckets
