### ISSUE TITLE
是否支持压缩

### ISSUE THREAD

**Issue by vmvz** [xujiajun/nutsdb#59]
以前一直用 http://ssdb.io/.

其中有一个选项
> leveldb.compression 压缩硬盘上的数据
> 最好设置为 yes! 如果是 yes, 一般你能存储 10 倍硬盘空间的数据, 而且性能会更>好.

如果不压缩, 我是不是要在存入前, 自行用zlib等进行压缩

**Comment by xujiajun** [comment]
@vmvz 嗯 目前 还没打算做压缩的选项。
