### ISSUE TITLE
索引模式的疑问

### ISSUE THREAD

**Issue by vmvz** [xujiajun/nutsdb#61]
看到文档关于索引模式的介绍, 我得出以下结论. 
请帮忙看理解是否正确? (有3个问题,Q1/Q2/Q3)
## HintKeyValAndRAMIdxMode 
 - (默认) 最快: 内存使用最大, key和value都放在内存, 
 - `**Q1**`数据量受限于内存? 我10G的数据量,就需要10GB内存?  (如果不是, 有没有一个数据给参考)
 - 支持其他结构 list\set\sorted set
## HintKeyAndRAMIdxMode 
 - 中等速度, 内存中等, 
 - 适合 value远大于key的场景效果
 - `**Q2**`以后有可能支持 sorted set吗?
 - `**Q3**`目前的GoLevelDB 最像这个模式?
## HintBPTSparseIdxMode 
- 最低速度, 内存最小, 极限省内存模式.

### 参考:
issue #33 里面说到
- 总元数据量15G左右,结果吃掉我80G的内存,而且我用的是HintKeyAndRAMIdxMode的方式
- 消耗内存是数据量的 3.46倍左右
所以我对于 索引模式的消耗内存情况不是很清晰了...

### 文档:
> 如果使用HintKeyAndRAMIdxMode的选项，读速度比默认配置低很多。道理很简单，默认配置是全内存索引，但是HintKeyAndRAMIdxMode的模式，是内存索引+磁盘混合的方式，但是这个选项模式可以保存远大于内存的数据。特别是value远大于key的场景效果更明显。
> 当前版本使用HintKeyValAndRAMIdxMode、 HintKeyAndRAMIdxMode和HintBPTSparseIdxMode 这三种作为db启动的时候索引模式。 默认使用HintKeyValAndRAMIdxMode。在基本的功能的string数据类型（put、get、delete、rangeScan、PrefixScan）这三种模式都支持。HintKeyValAndRAMIdxMode，作为数据库默认选项，他是全内存索引，读写性能都很高。他的瓶颈在于内存。如果你内存够的话，这种默认是适合的。另一种模式HintKeyAndRAMIdxMode，他会把value存磁盘，通过索引去找offset，这种模式特别适合value远大于key的场景，他的读性能要比起默认模式要降低不少。HintBPTSparseIdxMode这个模式（v0.4.0之后支持）这个模式非常省内存，使用多级索引，测试10亿数据，只占用80几MB的内存，但是读性能比较差，需要自己加缓存加速。具体看自己的要求选择模式。

**Comment by xujiajun** [comment]
@vmvz ，你好

Q1：具体你要实际测试下，这边涉及到map的扩容机制。一般来说会比实际大。
Q2：不太会支持了，至少目前来看。
Q3：不太了解

**Comment by vmvz** [comment]
@xujiajun 
- 如果使用场景 value远大于key + 想用 sorted set 就需要分库实现了?

- HintKeyAndRAMIdxMode 模式, 假设1GB的key, 100GB的value, 大约需要多少内存?, 是不是要我自己测试一下. 还是有大约的计算公式?
图片是ssdb的内存文档
![image](https://user-images.githubusercontent.com/1652700/81484839-851b1a00-927b-11ea-8a04-687ab90430ff.png)

**Comment by xujiajun** [comment]
@vmvz 想用 sorted set ，目前只有HintKeyValAndRAMIdxMode这个模式支持 ， 你最好自己测试下。
