### ISSUE TITLE
Set K/V 的时候, 重复写, 数据库不清理

### ISSUE THREAD

**Issue by vmvz** [xujiajun/nutsdb#62]
key不变, value变化
重复N次, 数据库可能存了N个,不会覆盖/清理

尝试用Merge方法, 也不会清理空间

**Comment by xujiajun** [comment]
@vmvz 嗯，当短时间内（如1s内）多次更新，会出现这个情况。但是实际生产环境一般不会出现同一个key短时间（1s内）又创建又更新的业务场景。

**Comment by xujiajun** [comment]
已经修复了 [#83](https://github.com/xujiajun/nutsdb/pull/83)
