### ISSUE TITLE
LRem与描述表现不一致

### ISSUE THREAD

**Issue by mzz2017** [xujiajun/nutsdb#66]
LRem描述为：
从指定bucket里面的指定的key的列表里移除前 count 次出现的值为 value 的元素。 这个 count 参数通过下面几种方式影响这个操作：

但并没有参数指定value，查看源码可发现该实现错误地类似于了LTrim。

**Comment by xujiajun** [comment]
@mzz2017 感谢指出。的确是有问题。

**Comment by mzz2017** [comment]
另外希望能有一个函数可以删除指定index（一个或多个）的数据

**Comment by mzz2017** [comment]
> 另外希望能有一个函数可以删除指定index（一个或多个）的数据

现在的策略只能是先LSet指定index的元素为一个特殊值，再使用LRem（修正后的）进行删除。我知道Redis中没有这个函数，但我认为它确实是有应用场景。

**Comment by xujiajun** [comment]
@mzz2017 收到
