### ISSUE TITLE
Add ListBuckets() and DeleteBucket() support

### ISSUE THREAD

**Issue by yamil-rivera** [xujiajun/nutsdb#68]
**Is your feature request related to a problem? Please describe.**
Yes. I currently need support for iterating through all existing buckets and then deleting each one including all their objects. I have not been able to find a satisfactory workaround.

**Describe the solution you'd like**
Adding tx.ListBuckets() and tx.DeleteBucket(bucket string) functions.

**Describe alternatives you've considered**
I have considered maintaining a bucket list and object count myself as a workaround but it's not ideal since for every tx.Put() I need to first check if the entity already exists or not in order to increase the bucket counter. This makes the approach very inefficient.

**Comment by xujiajun** [comment]
Hi
NutsDB v0.7.1 already supports delete bucket and  Iterate buckets, you can try it when you have time.

detail : https://github.com/xujiajun/nutsdb#using-buckets
