### ISSUE TITLE
bucket不存在是Get会返回错误

### ISSUE THREAD

**Issue by cossbow** [xujiajun/nutsdb#74]
如题，这种情况下返回的是一个errors.New()产生的错误，无法有效的判断bucket不存在，是否能返回一个固定的常量错误，或者返回nil，毕竟不存在不必抛出异常，而且并未提供检查bucket是否存在的方法

**Comment by xujiajun** [comment]
@cossbow 如果bucket不存在，不返回error，直接返回nil，如果想知道为什么取不到指定的key原因就没法知道。如果你想跳过这个错误，你可以Get的时候忽略掉就好了。关于没有提供检查bucket是否存在的方法，因为取的时候已经检查了，没必要重复检查。
