### ISSUE TITLE
NutsDB对并发的支持问题？

### ISSUE THREAD

**Issue by zxxf18** [xujiajun/nutsdb#76]
nutsdb对于并发访问有什么限制吗？

在多协程、多线程、多进程的情况下是否都支持，表现是怎么样的？

看了现有的小型kvdb，其中boltdb、leveldb不允许跨进程，上了文件锁
有一些小型kvdb可跨进程并发读，但不支持并发写(读写)

BerkeleyDB 支持多进程访问，不过协议是AGPL，用的时候需要注意
FastDB 支持多进程，但不是真正意义上的并发操作，一个进程写，另一个进程就要等
腾讯MMKV支持多进程，C++开发的

**Comment by xujiajun** [comment]
@zxxf18 nutsdb适合读多写少场景，多读可以并发读，但不支持并发写（读写）。
