### ISSUE TITLE
Potential memory leak problem with List type

### ISSUE THREAD

**Issue by tcd93** [xujiajun/nutsdb#81]
Hi, 

Correct me if i'm wrong, but with what I understand from your code, is that you always keep a copy of List/Set/Zset structures in memory, will that cause problems such as memory leak in the long run?

For example, with this line of code from `LRem` function:
https://github.com/xujiajun/nutsdb/blob/432dd3d0c87326ab039004c1b712f52ffc2b9f77/ds/list/list.go#L203
You only _re-adjusted_ the slice on top of `Items[key]` array, but the entire array is still there referenced by the slice, thus Garbage collector can not free the memory (even though it is inaccessible)

This [document](https://github.com/golang/go/wiki/SliceTricks#delete-without-preserving-order) & [so answer](https://stackoverflow.com/questions/28432658/does-go-garbage-collect-parts-of-slices) states that the "fix" is assigning the unused part to nil or Zero value
```
d := l.Items[key][:count-1]
d = nil
_ = d
```

Lemme know what you think

**Comment by tcd93** [comment]
Also the check here seems to be problematic:
https://github.com/xujiajun/nutsdb/blob/432dd3d0c87326ab039004c1b712f52ffc2b9f77/tx_list.go#L161-L163

If the List has 10 items  & I want to remove all 10 items, that would give me error.
I think this is mentioned in #66

**Comment by xujiajun** [comment]
@tcd93 Thank you for pointing it out. It seems to be a problem

**Comment by xujiajun** [comment]
I  have fixed this bug ,   detail: https://github.com/xujiajun/nutsdb/pull/92
