### ISSUE TITLE
start or end error,请问这是什么原因

### ISSUE THREAD

**Issue by blueskydata** [xujiajun/nutsdb#85]
ldb := db.GetLDB()
	tx,err := ldb.Begin(true)
	if err != nil {
		return nil,err
	}

	items, err := tx.LRange(BUCK, ASYNC_SEND_KEY, 0, -1)
	if err != nil {
		tx.Rollback()
		return nil,err
	}
开始几次是好的，后来就出现错误，请问这如何解决，谢谢！

**Comment by xujiajun** [comment]
@blueskydata hi,  能提供下完整的代码吗？还有你报什么错误，你是什么操作系统？什么版本的nutsdb，你这些不说清楚，我没法帮你查问题哈，你提供的越详细越好。

**Comment by xujiajun** [comment]
No reply for a long time, I closed it
