### ISSUE TITLE
Status of this nutsdb module/package ?

### ISSUE THREAD

**Issue by chmike** [xujiajun/nutsdb#90]
Is this module still actively supported ? 

In other words, can we  rely on this module/package for a production application ? 

What about the memory leak issue ? 

The websites https://xujiajun.cn/nutsdb/ and https://xujiajun.cn/nutsdb/ are not accessible.

**Comment by xujiajun** [comment]
@chmike hi，
 

> Is this module still actively supported ?
 
> In other words, can we rely on this module/package for a production application ?

yes,   this module still supported, “Active“ depends on whether I have time.
> What about the memory leak issue ?

I will fix it as soon as possible. This weekend will be the soonest

> The websites https://xujiajun.cn/nutsdb/ and https://xujiajun.cn/nutsdb/ are not accessible.

The website  https://xujiajun.cn/nutsdb/ built on GitHub Pages, so Whether it can be accessed depends on GitHub Pages. BTW I just tried, is able to access the website.
