### ISSUE TITLE
Is this production ready? Any users using it in production?

### ISSUE THREAD

**Issue by hiqsociety** [xujiajun/nutsdb#94]
Is this production ready? Any users using it in production?

great work by the way! i dont see how this is batched because it's not "Batch()" function. so how to batch them? this is from an example batch you have

 

                if err := db.Update(
                        func(tx *nutsdb.Tx) error {
                                for i := (j-1)*10000; i < j*1000; i++ {
                                        key := []byte("namename" + strconv2.IntToStr(i))
                                        val := []byte("valvalvavalvalvalvavalvalvalvavalvalvalvaval" + strconv2.IntToStr(i))
                                        if err := tx.Put(bucket, key, val, 0); err != nil {
                                                return err
                                        }
                                }
                                return nil
                        }); err != nil {
                                log.Fatal(err)
                        }

                }

**Comment by hiqsociety** [comment]
possible to update to 0.6? since it's 2019 since 0.5
https://github.com/xujiajun/nutsdb/releases/tag/v0.5.0

**Comment by xujiajun** [comment]
> possible to update to 0.6? since it's 2019 since 0.5
> https://github.com/xujiajun/nutsdb/releases/tag/v0.5.0

Yes，Today I will update to 0.6.

**Comment by xujiajun** [comment]
> Is this production ready? Any users using it in production?

see ：https://github.com/xujiajun/nutsdb/issues/27

**Comment by xujiajun** [comment]
> great work by the way! i dont see how this is batched because it's not "Batch()" function. so how to batch them? this is from an example batch you have

This example shows that it will only have one transaction commit. Otherwise, if you want to insert N records, you need to submit N transaction commits.

**Comment by hiqsociety** [comment]
do you have a db.Batch() function?

**Comment by xujiajun** [comment]
> do you have a db.Batch() function?

I don't have a db.batch () function ，but You can refer to my example and wrap it yourself
